// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dscgnebsdpxhdzcqwrgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzY2duZWJzZHB4aGR6Y3F3cmdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzIxMjMsImV4cCI6MjA3Mjg0ODEyM30.8tnx3P6ACpRRpYgkQXreGjofwx8EWlermjw4D2v-3mI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});